### ISSUE TITLE
Feature request: implement chatRequestOptions in API route

### ISSUE THREAD

**Issue by perezcarreno** [vercel-labs/ai-chatbot#104]
Is it possible to receive the chatRequestOptions from the useChat 'append' function in the /api/chat/route.ts file?

For context, I'm trying to set a different system message to createChatCompletion based on the example message choice in empty-screen.tsx.

I read the definition of the 'append' type, and it is supposed to support options to pass to the API call:
```javascript
 /**
     * Append a user message to the chat list. This triggers the API call to fetch
     * the assistant's response.
     * @param message The message to append
     * @param options Additional options to pass to the API call
     */
    append: (message: Message | CreateMessage, chatRequestOptions?: ChatRequestOptions) => Promise<string | null | undefined>;
```

However, if I send something like the following in empty-screen.tsx:

```javascript
...
export interface EmptyScreenProps {
  append: (
    message: {
      id: string
      content: string
      role: 'user' | 'system' | 'assistant'
    },
    chatRequestOptions?: ChatRequestOptions | undefined
  ) => void
}

export function EmptyScreen({ append }: EmptyScreenProps) {
  const handleExampleClick = (message: string, choice: number) => {
    append(
      {
        id: nanoid(),
        content: message,
        role: 'user'
      },
      { conversationChoice: choice }
    )
  }
...
```

I do not see it in route.ts if I'm logging the request or the body.

Is there a way to send data through the append function, as explained above? Thank you!

**Comment by MaxLeiter** [comment]
What kind of `ChatRequestOptions` are youe xpecting to pass? What is `conversationChoice`?

The type is defined here:

```
export type ChatRequestOptions = {
  options?: RequestOptions
  functions?: Array<ChatCompletionFunctions>
  function_call?: CreateChatCompletionRequestFunctionCall
}
```

If you want to send custom data, you can use the `body: { }` paramter in `useChat`: sdk.vercel.ai/docs/api-reference/use-chat#use-chat-options.

P.S. This issue belongs in https://github.com/vercel-labs/ai

**Comment by perezcarreno** [comment]
Thank you, @MaxLeiter ! Apologies for using the wrong parameter, and I'm sorry I sent the issue to the wrong place.

I tried sending custom data in the `body: {}` parameter in `useChat` and it works great! However, my question was geared towards being able to send the custom data from the 'append' function.

The use case is that from the empty-screen.tsx, we could add additional data so that it goes to useChat in the body.

So instead of just sending the id, content, and role for the message through append:
`export function EmptyScreen({ append }: EmptyScreenProps) {
  const handleExampleClick = (message: string) => {
    append({
      id: nanoid(),
      content: message,
      role: 'user'
    })
  }`

we could ideally send more data (in our case, an integer corresponding to a particular system message).

That way, when useChat hits route.ts, we can run:
`const res = await openai.createChatCompletion({
    model: 'gpt-4',
    messages: [systemMessage, ...messages],
    temperature: 0.7,
    stream: true
  })`

with a different systemMessage based on what the user selected on empty-screen.tsx. (Imagine systemMessage is a string that is set depending on the conversationChoice).

Does this make sense? I wouldn't want to send the actual system message from the client side because then people could change it to whatever they like. That's why we use an integer that represents a choice.

Perhaps I'm going about it the wrong way.

**Comment by MaxLeiter** [comment]
Ah I see. `append()` lets you pass an `options` param that is a RequestOptions. You can modify add information to the `body`.

**Comment by perezcarreno** [comment]
Thank you, @MaxLeiter ! I'll try that.
