### ISSUE TITLE
getting @resvg/resvg-wasm error in build on deployment

### ISSUE THREAD

**Issue by ChristianSchneeweiss** [vercel-labs/ai-chatbot#105]
after using the template the initial deploy fails with the following message. This happens locally too.
` WARN  GET https://registry.npmjs.org/@resvg/resvg-wasm/-/resvg-wasm-2.4.1.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.`

**Comment by leerob** [comment]
Hey there, I'm not able to reproduce. It could have been a temporary issue with NPM.
