### ISSUE TITLE
How yo implement a payment method? 

### ISSUE THREAD

**Issue by joseluistello** [vercel-labs/ai-chatbot#107]
Hi guys, I am in the process of learning Nextjs, in some projects I have been able to integrate Stripe as a payment method but I don't know how to do it when I have a third party api like openai, do you have any example of token limit or message limit?

**Comment by leerob** [comment]
Here's a template that uses Next.js and Stripe!

https://github.com/vercel/nextjs-subscription-payments

**Comment by joseluistello** [comment]
Thank you, @leerob
