### ISSUE TITLE
How to add a system message in the code?

### ISSUE THREAD

**Issue by proBhavesh** [vercel-labs/ai-chatbot#110]
HI, I wold like this chatbot to act like a professional Civil engineer. I want to provide a system message to it. How can I do it?

**Comment by MaxLeiter** [comment]
You can insert a custom message in the API route here: https://github.com/vercel-labs/ai-chatbot/blob/main/app/api/chat/route.ts#L33

Something like

```
messages: [{ role: "system", content: "you are a professional civil engineer" }, ...messages]
```

**Comment by proBhavesh** [comment]
It worked. Thanks for your help.

**Comment by raivatshah** [comment]
@MaxLeiter thanks for this. May I ask what would be the difference between the two methods?
