### ISSUE TITLE
Analytics.ts not used?

### ISSUE THREAD

**Issue by Markeljan** [vercel-labs/ai-chatbot#112]
How do we use Analytics.ts ?  Is this a preferred way to use Vercel Analytics?

Or is the recommended way from the docs fine:
<img width="699" alt="image" src="https://github.com/vercel-labs/ai-chatbot/assets/12901349/2980d441-593a-4808-a8a0-6c6519f24f3f">

**Comment by leerob** [comment]
Yes, that is the correct way! The code included here was unused. Deleted.
