### ISSUE TITLE
Autoscrolling doesn't work

### ISSUE THREAD

**Issue by johannesschaffer** [vercel-labs/ai-chatbot#114]
If the AI output is very long, e.g. creating a tailwind button with explanation, it doesn't autoscroll to the bottom.

**Comment by benhassineb** [comment]
Yes, I confirm. However, the strange thing is that it works on the demo site of https://chat.vercel.ai/.

**Comment by johannesschaffer** [comment]
When I wrote this, it didn't work on the example website either. If it works know, they are hopefully updating this repo here soon.

**Comment by leerob** [comment]
If you are still seeing this issue, we are open to community contributions to improve the scrolling behavior 🙏
