### ISSUE TITLE
localhost run dev not working

### ISSUE THREAD

**Issue by faye1225** [vercel-labs/ai-chatbot#123]
Followed the tutorial and started locally, but I get this error
<img width="800" alt="image" src="https://github.com/vercel-labs/ai-chatbot/assets/56664035/f2924f27-6844-4be0-86e0-30fdec5c84b4">

```
- error node_modules/next/dist/esm/server/lib/patch-fetch.js (253:23) @ originFetch
- error fetch failed
```

node version:v17.6.0

**Comment by Yougahei** [comment]
same problem， did u solve thise?

**Comment by leerob** [comment]
Please ensure you've added all of the environment variables correctly. If you are still seeing this, please provide a minimal reproduction of the code you've modified from the latest `main`. Thank you.
