### ISSUE TITLE
Unable to set NEXTAUTH_URL for Non-Vercel deployments

### ISSUE THREAD

**Issue by ramubotsplash** [vercel-labs/ai-chatbot#127]
I have changed NextJs Auth to use Google Provider and it works great in my local system (localhost:3000), however when trying in production mode with custom/ngrok  NEXTAUTH_URL, the application is still redirecting to http://localhost:3000

Steps taken:

1. Update Provider to Google and added env variables (fixed minor React/CSS issues)
```
providers: [
    GoogleProvider({
     clientId: process.env.GOOGLE_CLIENT_ID,
     clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ]
```
2. Run the NextJs app with command
```
NEXTAUTH_URL=https://<id>.ngrok-free.ap yarn run dev
NEXTAUTH_URL=https://<id>.ngrok-free.ap yarn run preview
```

Clicking "Login" button and going through Google Login flow is redirecting to http://localhost:3000 instead of domain name.  NEXTAUTH_URL is getting lost.

**Comment by Chelu97** [comment]
Hello, I would like to know if you managed to solve it because the truth is that I have been trying to see what is happening for a week now and I am desperate xD

**Comment by cahaseler** [comment]
This is a pretty major issue with this repository that makes it essentially useless unless you want to deploy to vercel. The fact that it's dependant on an obscure pre-release build of next-auth that prevents setting a custom url outside of vercel and that upgrading to a recent version of next-auth introduces Edge auth issues is very bad practice when it's supposed to be an example of how their new ecosystem just works. It just doesn't. You can't pretend it's a useful open-source library when it only works on infrastructure you sell.

**Comment by djsiroky** [comment]
I am also running in to this issue. I've tried quite a few workarounds/fixes, but still no luck it seems. Most likely I'll just move away from this template / NextAuth.

**Comment by bienp-r** [comment]
```
http://192.168.1.2:3000/sign-in?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2Fsign-in
```
Is this issue make like above? I just want to callbackUrl is using same hostname like 192.168.1.2. I try to insert `NEXTAUTH_URL` and `VERCEL_URL` to `.env`. But it didn't work.

I'm not sure why below code doesn't work.

```
const signInPage = config.pages?.signIn ?? "/api/auth/signin"
    if (request.nextUrl.pathname !== signInPage) {
      // Redirect to signin page by default if not authorized
      request.nextUrl.pathname = signInPage
      request.nextUrl.searchParams.set("callbackUrl", request.nextUrl.href)
      response = NextResponse.redirect(request.nextUrl)
    }
```

**Comment by leerob** [comment]
Updated to the latest NextAuth.js beta here, which will be stable soon: https://github.com/vercel-labs/ai-chatbot/pull/186
