### ISSUE TITLE
fail to run due to auth error?

### ISSUE THREAD

**Issue by dotku** [vercel-labs/ai-chatbot#130]
Any idea on the error like this?

When I login, I got something like

![image](https://github.com/vercel-labs/ai-chatbot/assets/1519232/c7beb96b-d5f4-4a7d-bca1-9adc333fc445)

with log report

```
    at (node_modules/.pnpm/@auth+core@0.0.0-manual.8fcd46b0/node_modules/@auth/core/lib/assert.js:46:15)
    at (node_modules/.pnpm/@auth+core@0.0.0-manual.8fcd46b0/node_modules/@auth/core/index.js:70:28)
    at (node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:210:36)
```

**Comment by stebou** [comment]
the same thing

**Comment by Hewlbern** [comment]
same thing

**Comment by ikirudesign** [comment]
It would actually be nice if we had a fork of this repo without authentication. I'm still new to the whole Vercel ecosystem and I just wanted to apply the slick GPT like chat UI to an existing agent I trained.

**Comment by dotku** [comment]
The other option you could try would be the higingface chat UI.

**Comment by wan-mureithi** [comment]
Also got this error, but when I added AUTH_SECRET and NEXTAUTH_URL on the .env file it resolved the issue. @dotku 
[Next auth issue](https://github.com/nextauthjs/next-auth/issues/3245)
https://next-auth.js.org/errors

**Comment by leerob** [comment]
You are likely missing the correct environment variables, as mentioned above 🙏 Please ensure those are added.

**Comment by AlexKalopsia** [comment]
@leerob it would be great if this info was present in the docker installation guide, as it seems to be a necessary step to get it to work 🙏
