### ISSUE TITLE
Can next-auth 4.22.3 work with this repo?

### ISSUE THREAD

**Issue by harrywang** [vercel-labs/ai-chatbot#132]
I noticed that "next-auth": "0.0.0-manual.83c4ebd1" is used - I have another project using 4.22.3 and I want to share authentication between the two projects - it seems that I cannot integrate them due to the different versions of next-auth. 

Can anyone help me with some pointers?

**Comment by eyeHORUSdotETH** [comment]
I'm having this issue too. I built out a decent amount of a project off of this repo and just tried switching to next-auth 4 and getting this error 

> - error node_modules/.pnpm/oidc-token-hash@5.0.3/node_modules/oidc-token-hash/lib/shake256.js (5:0) @ <unknown>
> - error Cannot read properties of undefined (reading 'substring')

**Comment by harrywang** [comment]
answered here https://github.com/nextauthjs/next-auth/issues/8275#event-10052055368
