### ISSUE TITLE
Custom data chatbot?

### ISSUE THREAD

**Issue by Mbensler** [vercel-labs/ai-chatbot#134]
Can this template be used to create a chatbot that is trained on your own custom data?

**Comment by ali-issa** [comment]
Before opening issues in a repo, it's a good practice to carefully review the README.md file. Similarly, consult the documentation when utilizing any library before seeking help.

https://github.com/vercel-labs/ai-chatbot#features

**Comment by ali-issa** [comment]
This template won't help you with training a model on custom data. If you're interested in fine-tuning an OpenAI model, you can find more information [here](https://platform.openai.com/docs/guides/fine-tuning). To "train" a model, begin with an open-source model and conduct research on the topic.

**Comment by 0x-Legend** [comment]
Yes, you can use OpenAI fine tuning.

**Comment by leerob** [comment]
^ Yeah, you can use fine tuning, was well as new RAG capabilities with OpenAI. Or fork it and talk to really any LLM. This is just a starting point!
