### ISSUE TITLE
Slide out menu

### ISSUE THREAD

**Issue by wolfpixels** [vercel-labs/ai-chatbot#136]
Hi,

Pretty trivial but is there a way to have the menu for chat history like it's shown in the demo?
The one that's showing when running locally is sliding out over page, I prefer the one that slides out, making the rest of page shrink.

Thanks

**Comment by lucasjinreal** [comment]
Same

**Comment by PaoloJN** [comment]
same

**Comment by dariogcode** [comment]
Same
