### ISSUE TITLE
Auth providers other than GitHub fail

### ISSUE THREAD

**Issue by natty-zs** [vercel-labs/ai-chatbot#142]
I've tried swapping in the google and auth0 providers, and something is causing it to throw an Unauthorized error when you submit a new message to the chat. The login flow appears to work, takes me through to the oauth app consent, and redirects back, user name and avatar populate. But then the Unauthorized error [in api/chat/route.ts] pops when you enter a message. I've tried adding in updated configuration for the provider as well, but nothing seems to work.

**Comment by natty-zs** [comment]
#122 fixed this. Not sure why this isn't documented anywhere. Is this happening because the repo uses the experimental branch of next-auth?

**Comment by spookymargiela007** [comment]
Hey natty, you're right this isn't documented anywhere but likely a common need for users of this project to trade out the Auth, 
I've been running into the issue you had with Next-Auth Google Provider. I made some updates globally to support profile.sub and profile.id in the JWT callback function but now having issues displaying the retrieved chat history at a specific URL endpoint .ie /chat/12345. How did you manage to get your auth fully working?

**Comment by spookymargiela007** [comment]
Thanks @natty-zs just dropped a comment in that thread
