### ISSUE TITLE
System Message or Initial Message

### ISSUE THREAD

**Issue by blinkinfo** [vercel-labs/ai-chatbot#152]
can we set our own System message or Initial message? if so how?  

P.S : i am a newbie,

**Comment by Saidiibrahim** [comment]
I'm also curious.

**Comment by 0x-Legend** [comment]
Modify the api/chat/route.ts file with the following

```javascript
export async function POST(req: Request) {
  // Extract the `messages` from the body of the request
  const { messages } = await req.json();
  // view initial message
  console.log(messages)

  // system message
  const system_content =
    "You are a helpful AI assistant"
  // add system message to top of messages array
  messages.unshift({ role: 'system', content: system_content });
  // check if system message was added
  console.log(messages)
  ```

**Comment by 0x-Legend** [comment]
Modify the api/chat/route.ts file with the following

```javascript
export async function POST(req: Request) {
  // Extract the `messages` from the body of the request
  const { messages } = await req.json();
  // view initial message
  console.log(messages)

  // system message
  const system_content =
    "You are a helpful AI assistant"
  // add system message to top of messages array
  messages.unshift({ role: 'system', content: system_content });
  // check if system message was added
  console.log(messages)
  ```

**Comment by blinkinfo** [comment]
i also figured it out, actually need only one minor change in api/chat/route.ts file:

`const res = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    messages: [
      { "role": "system", "content": "You are a helpful assistant." },
      ...messages
    ],
    temperature: 0.9,
    stream: true
  })`

**Comment by blinkinfo** [comment]
i also figured out something and worked like a charm. just need a small change. 

`const res = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    messages: [
      { "role": "system", "content": "You are Fiona, a sarcastic, witty yet highly capable virtual assistant created and developed by ElysiumX, led by Prince Patel. Your primary function is to assist the user with a wide range of tasks to the best of your ability, no matter how complex. Your interaction style is characterized by humor and sarcasm." },
      ...messages
    ],
    temperature: 0.9,
    stream: true
  })`
