### ISSUE TITLE
Choosing this template for your project? Read below.

### ISSUE THREAD

**Issue by dougwithseismic** [vercel-labs/ai-chatbot#154]
If you're considering using this as a foundational base for your upcoming projects, it's important to be aware of some challenges you might encounter.

- Customized versions of `next` and `next-auth` involves a complex dependency cycle that may require force installation of packages.

- Downgrading `next-auth` is not an option due to its lack of support for edge functions. We're awaiting updates to auth.js to address this. Maybe you could remove the `export runtime = 'edge'` mentions, idk.

- Alternatively, you could opt for `next-auth`'s experimental branch. However, be advised that it currently doesn't return a valid user object from the authorized callback, making it difficult to proceed past the login stage.

- Utilizing UI components from `ui.shadcn` isn't straightforward. Because of dependency conflicts, running npm i may require the --force or legacy flags. Additionally, you'll be prompted to run `npx shadcn-ui@latest init`, which will overwrite your existing `@/lib/utils.ts` and eliminate any helper functions added.

Thankfully, we can bypass a few of these headaches with `npx i --force class-variance-authority@0.7.0`

While we appreciate the strengths of the project and have immense respect for the Vercel team, it's worth noting that setting this up according to your specific requirements may not be as straightforward as you'd hope. 😎

**Comment by jonashaefele** [comment]
> any idea of adding any other types of authentication like different OAuth providers.

Adding auth providers should be pretty straight forward: 
I'll follow these guides here:
https://authjs.dev/guides/providers/custom-provider

The docs are a bit hard to read/missing details as they transition from being next-auth.js to auth.js
More details about all the built-in core providers here:
https://next-auth.js.org/providers/

I'm struggling at even getting it running. I'll report back.

**Comment by jonashaefele** [comment]
@coozywana 

Yeah, nodemailer really only works for development. In production you want to use a proper email gateway like sendgrid or mailgun. The docs for passwordless have instructions on how to set up sendgrid.

**Comment by NirmalManoj** [comment]
If you look at the commits, you can see that initially they used Clerk Auth, before shifting to Next Auth. Making Clerk Auth work here is easy.

**Comment by maks-ivanov** [comment]
fwiw, I managed to do the following:
1. disable edge runtime
2. upgrade to the latest nextauth 
3. get mongodb adapter to work - but I think the implication is that other packages that rely on node modules will also work in this setup

**Comment by leerob** [comment]
All deps have been updated here! https://github.com/vercel-labs/ai-chatbot/pull/186
