### ISSUE TITLE
ai-chatbot   where is the KV_URL used ?

### ISSUE THREAD

**Issue by sytpb** [vercel-labs/ai-chatbot#155]
deploy on locally , where is the KV_URL used ? I searched the code , not found somthing about the KV_URL , so I am confused !

**Comment by maddo7** [comment]
I would assume their `import { kv } from '@vercel/kv'` package looks for this internally so you won't find it in the code.

**Comment by leerob** [comment]
^ Correct, it's used by Vercel KV.
