### ISSUE TITLE
Vercel's Chatbot with Langchain, Pinecone and Vercel Kv BOUNTY

### ISSUE THREAD

**Issue by scottklein7** [vercel-labs/ai-chatbot#157]
Hi everyone!

After playing with this repo for a little bit, I am stuck on implementing some key features I need such as langchain, pinecone and vercel kv. I want the app to function in the exact same manner as it does now, just using a custom knowledge base with my pinecone vector store and utilizing langchain.

If anyone has resources on this, I would greatly appreciate a pointer! 

Or, if anyone is willing to build this for me, let me know here.

**Comment by carlosrziegler** [comment]
Not with Vercel KV but you can see how it workks with pinecone
https://github.com/CarlosZiegler/next-ai
