### ISSUE TITLE
Page Speed of chat.vercel.ai

### ISSUE THREAD

**Issue by capsloq** [vercel-labs/ai-chatbot#158]
I have not analysed the results in depth but i am used to NextJS being super fast and usually crushing Pagespeed Insights  in a good way.

Before getting into this project i did a quick check and was surprised that this project fails the core web vitals. Is there any potential for optimizations?

![image](https://github.com/vercel-labs/ai-chatbot/assets/73945900/2a47c386-d734-4a51-82ce-e9ed8ca96b17)

**Comment by leerob** [comment]
Definitely some optimizations we can make here 😄 We'll take a look, thank you!
