### ISSUE TITLE
Persistence implementation too expensive

### ISSUE THREAD

**Issue by bcldvd** [vercel-labs/ai-chatbot#163]
I've been using this wonderful template for the past week, and I'm already at 7k requests on the 30k limit. With more than 1k requests yesterday alone...

<img width="482" alt="image" src="https://github.com/vercel-labs/ai-chatbot/assets/569053/b8bfca62-78c0-4c9a-a4ef-8a38ab2691b2">

I'm the only one using the app, locally.... 😅 This won't scale at all with actual users.

Is the KV request limit too low or is the way conversation history retrieval has been implemented done wrong?

**Comment by 0x-Legend** [comment]
Vercel KV is expensive.

Try using something like supabase instead:
guide: [https://github.com/supabase-community/vercel-ai-chatbot](url)
