### ISSUE TITLE
Type error: Property 'className' does not exist on type 'AlertDialogPortalProps'.

### ISSUE THREAD

**Issue by sytpb** [vercel-labs/ai-chatbot#165]
npm run build got error 

Type error: Property 'className' does not exist on type 'AlertDialogPortalProps'.

  12 | 
  13 | const AlertDialogPortal = ({
> 14 |   className,
     |   ^
  15 |   children,
  16 |   ...props
  17 | }: AlertDialogPrimitive.AlertDialogPortalProps) => (

**Comment by almaziphone** [comment]
me too

**Comment by atrhacker** [comment]
any solutions or temporary fix on this ?

**Comment by leerob** [comment]
Solved here: https://github.com/vercel-labs/ai-chatbot/pull/186
