### ISSUE TITLE
[auth][error]  Host must be trusted. 

### ISSUE THREAD

**Issue by sytpb** [vercel-labs/ai-chatbot#169]
After run  npm run build , 
then npm run start on my cloud server,   the error show me like that , 

`[auth][error][UntrustedHost]: Host must be trusted. 
URL was: http://159.138.*.*:3000//api/auth/session. Read more at https://errors.authjs.dev#untrustedhost`

**Comment by leerob** [comment]
Please ensure you have the correct environment variables in your setup 🙏
