### ISSUE TITLE
Error when running LangChain with certain providers: Module not found: Can't resolve 'http'

### ISSUE THREAD

**Issue by coozywana** [vercel-labs/ai-chatbot#170]
**Issue Description:**
I'm encountering an issue while trying to integrate Google PaLM into the LangChain for Route.js framework. This issue prevents the expected behavior of the integration. Here are the details:

**Steps to Reproduce:**
Add Google PaLM into the LangChain for Route.js.

**Expected Behavior:**
It should work normally.
**Actual Behavior:**
```error ./node_modules/.pnpm/agent-base@7.1.0/node_modules/agent-base/dist/helpers.js:28:27 Module not found: Can't resolve 'http'```
**Environment:**
- Node.js version: v18.14.1
Thanks

**Comment by leerob** [comment]
Hey there, unfortunately I'm not sure what your issue is here. Maybe try making a small reproduction to see where it could be? I haven't used PaLM personally.
