### ISSUE TITLE
examples for components/ui

### ISSUE THREAD

**Issue by ramnavan** [vercel-labs/ai-chatbot#174]
There are a bunch of radix components under components/ui like input, textarea, sheet. I don't see these components referenced anywhere. I'm curious what these components are for? 

I'm interested in rendering custom UI elements within the chat-message itself. Would love to get some examples of such usecases.

**Comment by clodal** [comment]
They are from @shadcn/ui Follow the installation steps [here](https://ui.shadcn.com/docs/installation/next) to get the,

**Comment by ramnavan** [comment]
@clodal - My question is that almost all these components were not utilized in this codebase. I was wondering about that. And if these components are supposed to be used as part of the chat component, I wonder how to go about it

**Comment by leerob** [comment]
There might be some additional components here that didn't end up getting used - they can be removed!
