### ISSUE TITLE
A silly question but

### ISSUE THREAD

**Issue by SmartDever02** [vercel-labs/ai-chatbot#178]
When I check the code, we have "signin with google" button in the page but when I check this url
https://chat.vercel.ai/
I see login with vercel.
why is it?
And also if I run the code in my local it's getting redirected to /signin page with redirectUrl = localhost:3000
That causes critical issue in my app.
How can I solve this :pray:

**Comment by leerob** [comment]
The login with Vercel version is only for the hosted example, as an anti-spam, anti-bot preventative measure.
