### ISSUE TITLE
google avatar can't load . 

### ISSUE THREAD

**Issue by sytpb** [vercel-labs/ai-chatbot#180]
I add google to support login , login feature is OK , but , I can't get avatar of my google account . 
the error shows , 
`upstream image response failed for https://lh3.googleusercontent.com/a-/ALV-UjWdxBT_8th5IAVgRZAtW0tw7vdoKpgWw0urUr0bKhqs=s96-c&s=60 400`

```
export const {
  handlers: { GET, POST },
  auth,
  CSRF_experimental // will be removed in future
} = NextAuth({
  providers: [GitHub,Google({
    clientId: process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET
  })],
  callbacks: {
    jwt({ token, profile }) {
      if (profile?.sub) { // Google profiles have a 'sub' field
        token.id = String(profile.sub);
        token.image = profile.picture;
      } else if (profile?.id) { // GitHub profiles have an 'id' field
        token.id = profile?.id;
      }
      if (profile) {

      }
      
      return token
    },
    authorized({ auth }) {
      console.log(auth)
      return !!auth?.user
    }
  },
  pages: {
    signIn: '/sign-in' 
  }
})
```

![image](https://github.com/vercel-labs/ai-chatbot/assets/12178686/58e4f5a2-b6b1-4443-ac64-f795afc7da2e)

why the additional &s=60 ???

**Comment by sytpb** [comment]
find here 
` src={user?.image ? `${user.image}&s=60` : ''}`

user-menu.tsx  

why using &s=60 ?

**Comment by vincor1986** [comment]
> why using &s=60 ?

I think this is due to the configuration in `next.config.js` file in the src folder. It's trying to optimise the image from Github using syntax that works with Github avatars but doesn't work with Google user avatars. 

You can change the `images` property in the `next.config.js` module export to be include Google as follows, which worked for me:

```
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'avatars.githubusercontent.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'lh3.googleusercontent.com',
        port: '',
        pathname: '**',
      },
    ],
  },
```

I hope that helps!

**Comment by leerob** [comment]
^ looks resolved 👍
