### ISSUE TITLE
Dependency problems: next and next-auth packages

### ISSUE THREAD

**Issue by alberduris** [vercel-labs/ai-chatbot#184]
In packages.json the versions for `next` and `next-auth` are:

```
"next": "13.4.7-canary.1",
"next-auth": "0.0.0-manual.83c4ebd1",
```

Which is causing a `ERESOLVE unable to resolve dependency tree` error:

```
npm ERR! While resolving: next-template@0.0.2
npm ERR! Found: next@13.4.7-canary.1
npm ERR! node_modules/next
npm ERR!   next@"13.4.7-canary.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^13.4.6" from next-auth@0.0.0-manual.83c4ebd1
npm ERR! node_modules/next-auth
npm ERR!   next-auth@"0.0.0-manual.83c4ebd1" from the root project
```

I have managed to solve it by changing the dependencies from packages.json to the following:
```
"dependencies": {
  ...
  "next": "latest",
  "next-auth": "beta",
  "class-variance-authority": "^0.7.0",
  ...
},
...
"devDependencies": {
  ...
  "typescript": "^5.2.2"
  ...
}
```

Using the same versions as in the official NextAuth example app: https://github.com/nextauthjs/next-auth-example/blob/main/package.json.

However, I feel that this solution is a bit hacky and may cause other problems. Can you provide any insights on this?

**Comment by leerob** [comment]
Fixing here: https://github.com/vercel-labs/ai-chatbot/pull/186

**Comment by alberduris** [comment]
Thanks @leerob! Much appreciated!
