### ISSUE TITLE
KV_REST_API_URL and KV_REST_API_TOKEN are required for parts of app

### ISSUE THREAD

**Issue by SumitBando** [vercel-labs/ai-chatbot#31]
.. and are not documented.

**Comment by CarlosZiegler** [comment]
Env example and readme was updated:
<img width="966" alt="image" src="https://github.com/vercel-labs/ai-chatbot/assets/38855507/03e439ea-c030-4bdd-a13c-d88d44f58567">

<img width="479" alt="image" src="https://github.com/vercel-labs/ai-chatbot/assets/38855507/e9f114a4-bb00-4015-9f84-d4c5d002aa15">
