### ISSUE TITLE
Warning metadata on development mode

### ISSUE THREAD

**Issue by yuxxeun** [vercel-labs/ai-chatbot#33]
i got this warning when running on development mode (localhost) `warn metadata.metadataBase is not set for resolving social open graph or twitter images, fallbacks to "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase`

**Comment by fotoflo** [comment]
same

**Comment by DerekAlanGilbert** [comment]
I also get this error when ever I reload.

**Comment by Markeljan** [comment]
just adding: metadataBase: new URL('https://acme.com') this worked (using my sites url)
also pnpm showing no errors/warnings so using that may help as well

**Comment by yuxxeun** [comment]
thank you for y'all to respond this issue, very helping
