### ISSUE TITLE
Sytax highlighting not working

### ISSUE THREAD

**Issue by karlbateman** [vercel-labs/ai-chatbot#45]
Noticed a strange issue with code blocks not always using syntax highlighting. I'm not sure if this is an issue with the Markdown parser or the OpenAI response doesn't always include language in the markdown codeblock.

![image](https://github.com/vercel-labs/ai-chatbot/assets/33239151/d55044af-2731-4221-bf6c-eef671f8797a)

**Comment by leerob** [comment]
We're open to community contributions here to make this better! 🙏
