### ISSUE TITLE
Unhandled Runtime Error When Unauthorized

### ISSUE THREAD

**Issue by leohxj** [vercel-labs/ai-chatbot#46]
clone and run this repo first time, chat request is not authorized, but the site window got a runtime error:

![image](https://github.com/vercel-labs/ai-chatbot/assets/1506900/88ab08cb-b630-47ea-b5dd-b958e2b8e6ea)

then I set onError options for `useChat` hook, it still happens.

**Comment by YYvanYang** [comment]
same error+1

**Comment by ZiggStardust** [comment]
+1

**Comment by ZiggStardust** [comment]
If you add VERCEL_ENV="preview" to the .env this resolves the app/api/chat/route.ts request issue - if that's the error your getting

**Comment by kahirokunn** [comment]
same error+1

**Comment by Austin88-pro** [comment]
Unsubscribe.


Sent from Yahoo Mail for iPhone


On Tuesday, June 20, 2023, 9:48 PM, kahirokunn ***@***.***> wrote:




same error+1

**Comment by jaredpalmer** [comment]
This is now resolved as we are now forcing auth, even on preview deployments.

**Comment by jaredpalmer** [comment]
If you continue to see this problem, please re-open
