### ISSUE TITLE
Strange question marks in cyrillic symbols

### ISSUE THREAD

**Issue by TimPchelintsev** [vercel-labs/ai-chatbot#47]
Hi! Thanks for great lib. It seems like a decoding issue:
<img width="763" alt="Screenshot 2023-06-19 at 07 38 59" src="https://github.com/vercel-labs/ai-chatbot/assets/3499434/9321e888-0491-43ee-949f-f4125c1cf841">

Screenshot from Vercel demo project https://chat.vercel.ai

It seems it works nice locally, so maybe this bug is somehow related to Vercel?

**Comment by leerob** [comment]
https://github.com/vercel-labs/ai-chatbot/pull/61#issuecomment-1599771913
