### ISSUE TITLE
It's tough to type in Japanese!!

### ISSUE THREAD

**Issue by chihiros** [vercel-labs/ai-chatbot#48]
Watch the video.
In the case of Japanese input, when you convert from Hiragana to Kanji,
the text is sent with that Enter press. I would like it to be corrected.

https://github.com/vercel-labs/ai-chatbot/assets/64934951/e576e862-01b0-4bb4-830a-168644c9ac75

**Comment by justjavac** [comment]
I fixed the issue with the Chinese input method, perhaps it will work properly in Japanese as well. https://github.com/vercel-labs/ai-chatbot/pull/63

**Comment by chihiros** [comment]
@justjavac 
oo, thanks you!
