### ISSUE TITLE
The Edge Function "middleware" is referencing unsupported modules: - next: stream, fs, url

### ISSUE THREAD

**Issue by gcphost** [vercel-labs/ai-chatbot#49]
When deploying to my vercel hobby account I received the error and had to remove middleware to deploy.

**Comment by balazsorban44** [comment]
Could you link to your project so we can have a look? :pray:

**Comment by gcphost** [comment]
I invited you to the repo, Vercel is @gcphost/asked-io

**Comment by balazsorban44** [comment]
Hmm the reproduction doesn't have a middleware file. 🤔

**Comment by gcphost** [comment]
In order to deploy the site I had to remove the middleware file.

**Comment by gcphost** [comment]
Re-added and now it appears to be building today.
