### ISSUE TITLE
How to fix this about 'NOW_SANDBOX_WORKER_MAX_MIDDLEWARE_SIZE'

### ISSUE THREAD

**Issue by wengshuang** [vercel-labs/ai-chatbot#52]
![image](https://github.com/vercel-labs/ai-chatbot/assets/80451560/72c4f0b2-61fd-4bad-9656-d7f04e69ffbd)

**Comment by leohxj** [comment]
remove runtime edge and try again?

**Comment by wengshuang** [comment]
link this?
![image](https://github.com/vercel-labs/ai-chatbot/assets/80451560/df506aca-999b-4391-a727-67ec47155354)

**Comment by tomas2387** [comment]
You can also delete the whole app/share/[id] folder and get in the size limits
![image](https://github.com/vercel-labs/ai-chatbot/assets/2075943/6c5b86a6-b150-466c-bce1-86134726ec86)
