### ISSUE TITLE
Next-auth version?

### ISSUE THREAD

**Issue by morganpartee** [vercel-labs/ai-chatbot#54]
Hey it looks like auth was pinned to a commit that doesn't exist anymore maybe? Moving to a main version of next auth seems to break the app.

Version is

    "next-auth": "0.0.0-manual.4cd21ea5",

Which no longer resolves when installing dependencies

**Comment by balazsorban44** [comment]
It should still be available, maybe npm was down?: https://www.npmjs.com/package/next-auth/v/0.0.0-manual.4cd21ea5

The version of `next-auth` used in this repo is currently being worked on and is available under the `next-auth@experimental` distribution tag.

See https://github.com/nextauthjs/next-auth/pull/7443 for more details.

**Comment by anusheel** [comment]
Might be better to just switch to the latest versions. I confirmed that it works

```
    "next": "13.4.9-canary.1",
    "next-auth": "experimental",
```

**Comment by swyxio** [comment]
@shuding recommend reopening since this is still an issue

**Comment by balazsorban44** [comment]
Clarification in https://github.com/vercel-labs/ai-chatbot/issues/89#issuecomment-1621630872, if you followed the steps there and still have issues, let's open a new one with a reproduction, thanks! :pray:
