### ISSUE TITLE
Unhandled Runtime Error  Error: Unauthorized

### ISSUE THREAD

**Issue by khaledahmadi** [vercel-labs/ai-chatbot#73]
Hello everyone,

I'm reaching out for assistance regarding an issue I'm facing while following the documentation. I have diligently followed all the instructions and properly configured the .env and .env.local files as specified. However, despite these efforts, I'm still encountering an error.

I would greatly appreciate any guidance or support you can provide to help me resolve this matter. If there are any additional steps or troubleshooting suggestions that I may have missed, please let me know.

Thank you for your attention and assistance in 

Error i am Facing
<img width="1435" alt="Screenshot 2023-06-21 at 10 02 23 PM" src="https://github.com/vercel-labs/ai-chatbot/assets/26869332/e95245cc-bf05-4c3c-91ac-8e27c4df5084">

My .env configuration file 
<img width="925" alt="Screenshot 2023-06-21 at 10 03 00 PM" src="https://github.com/vercel-labs/ai-chatbot/assets/26869332/0e965771-f035-4625-b34d-13901af709df">

My .env.local configuration file 
<img width="842" alt="Screenshot 2023-06-21 at 10 11 51 PM" src="https://github.com/vercel-labs/ai-chatbot/assets/26869332/2ab92d86-132a-4d82-bdad-209b80e31c4c">

**Comment by tomas2387** [comment]
Where's your `OPENAI_API_KEY`?

**Comment by jaredpalmer** [comment]
This should be fixed now. This will only show during previews when there is no auth key and not preview token has been inserted

**Comment by khaledahmadi** [comment]
> Where's your `OPENAI_API_KEY`?

i have it in local pc and didn't add in the screenshot

**Comment by khaledahmadi** [comment]
> This should be fixed now. This will only show during previews when there is no auth key and not preview token has been inserted

i have cloned the latest repository and followed the documentation properly but still i am facing the mentioned issue

**Comment by satpalsr** [comment]
Additional api key checks must also be introduced to catch any error generated from [here](https://github.com/vercel-labs/ai-chatbot/blob/1b5811df53687793fbd84a502b541dd81f4bca15/app/api/chat/route.ts#L27)
