### ISSUE TITLE
Can't sign in with Github (Deployed on Vercel)

### ISSUE THREAD

**Issue by cachho** [vercel-labs/ai-chatbot#78]
I just deployed this on Vercel and I can't sign in with Github. I already redeployed and recloned.

Here are all the changes I did.

1. Add the required keys (OPENAI_API_KEY, AUTH_GITHUB_SECRET, AUTH_GITHUB_ID)
2. Rename opengraph-image.tsx and remove the export const runtime = 'edge' line
3. Redeploy
4. Fix the `https://errors.authjs.dev#errors_missingsecret` error by adding a `NEXTAUTH_SECRET` environment variable. Redeploy.
5. Add `https://nextjs-chat-DOMAIN.vercel.app/` as my Homepage URL and `https://nextjs-chat-domain.vercel.app/api/auth/callback/github` as `Authorization callback URL` for the Github oauth app.

This is what it's leaving me with

![Screenshot 2023-06-22 230137](https://github.com/vercel-labs/ai-chatbot/assets/14180064/b5ce29ee-ef77-42a5-8ec2-d4437ba180c4)

The logs look normal (this is my first time deploying on vercel, I don't know how to expand them)
![Screenshot 2023-06-22 230636](https://github.com/vercel-labs/ai-chatbot/assets/14180064/16bf23f1-37bf-4d8e-9616-b30e17bfb0c3)

I also tried to run it locally, I changed the `Authorization callback URL` but the result is the same.

**Comment by cachho** [comment]
I found #28 and changed the callback url to `https://nextjs-chat-DOMAIN.vercel.app/api/auth/callback/github` but still get the issue.

**Comment by balazsorban44** [comment]
could you add a reproduction? the deployed example mentioned here https://github.com/vercel-labs/ai-chatbot/issues/28#issuecomment-1602571012 works.

**Comment by cachho** [comment]
> could you add a reproduction? the deployed example mentioned here [#28 (comment)](https://github.com/vercel-labs/ai-chatbot/issues/28#issuecomment-1602571012) works.

sure, I made it public but what I described as step 2 is the only thing that I actually changed in the code base: https://github.com/cachho/nextjs-chat

**Comment by cresencio** [comment]
Had the same issue and resolved following the suggestion from @balazsorban44, however my lock file references 0.0.0-manual.223c6467 and the Vercel server logs were failing to deploy. I checked the logs and one of the messages suggested running `pnpm install --no-frozen-lockfile`. I did that locally and then pushed to main and the build was successful. The Github login worked too. 

Before doing that, I also added the NEXTAUTH_SECRET generated from https://generate-secret.vercel.app/32

**Comment by balazsorban44** [comment]
@cacho can you run `pnpm up @auth/nextjs` in your project? Your [lockfile](https://github.com/cachho/nextjs-chat/blob/a841df1f7814dd6a2c86e30078be3104c335927c/pnpm-lock.yaml#L178) suggests you forgot to follow https://github.com/vercel-labs/ai-chatbot/issues/28#issuecomment-1602571012

You can see the available versions at https://www.npmjs.com/package/@auth/nextjs?activeTab=versions As of writing, the latest `experimental` version is [0.0.0-manual.179c08d4](https://www.npmjs.com/package/@auth/nextjs/v/0.0.0-manual.179c08d4) but you are on an 11 days old version.

@cresencio will need a reproduction.

**Comment by cachho** [comment]
> @cacho can you run `pnpm up @auth/nextjs` in your project? Your [lockfile](https://github.com/cachho/nextjs-chat/blob/a841df1f7814dd6a2c86e30078be3104c335927c/pnpm-lock.yaml#L178) suggests you forgot to follow [#28 (comment)](https://github.com/vercel-labs/ai-chatbot/issues/28#issuecomment-1602571012)

Still the same stuff I've seen before. After a while the github authorize page opens, I authorize and then I get back to the sign in page. After spamming the button I get a "try signing in with a different account".

![image](https://github.com/vercel-labs/ai-chatbot/assets/14180064/fe66983c-53e6-459c-926c-342cacabb1e8)

My repo has been updated.

**Comment by cresencio** [comment]
@balazsorban44 - the issue seems to have gone away! All I did was clear my cache 🤷‍♂️ But thanks anyway!

**Comment by balazsorban44** [comment]
FYI: I've added some improvements in this PR https://github.com/vercel-labs/ai-chatbot/pull/80 which is waiting for approval/merge.

**Comment by balazsorban44** [comment]
@cachho your description's 5th step says:

> Add https://nextjs-chat-DOMAIN.vercel.app/ as my Homepage URL and Authorization callback URL for the Github oauth app.

This is wrong. The callback URL needs to be: https://nextjs-chat-DOMAIN.vercel.app/api/auth/callback/github as documented at https://authjs.dev/reference/core/providers_github#callback-url

That might be the issue!

**Comment by cachho** [comment]
> @cachho I noticed that your description's 5th step says:
> 
> > Add https://nextjs-chat-DOMAIN.vercel.app/ as my Homepage URL and Authorization callback URL for the Github oauth app.
> 
> This is wrong. The callback URL needs to be: https://nextjs-chat-DOMAIN.vercel.app/api/auth/callback/github as documented at https://authjs.dev/reference/core/providers_github#callback-url
> 
> That might be the issue!

sorry, I did not describe that right (I will correct my original post). I already made that change, please take a look at the screenshot I posted: https://github.com/vercel-labs/ai-chatbot/issues/78#issuecomment-1603376350

And thanks for the help!

**Comment by balazsorban44** [comment]
Hmm. Maybe take a look at https://github.com/vercel-labs/ai-chatbot/pull/80

After the applied changes there, not only login works when deployed: https://ai-chatbot.vercel.sh/ but it also supports OAuth login on preview deployments, eg: https://ai-chatbot-1qzzt58mx.vercel.sh/

So this is definitely a configuration issue, or an outdated version of `next-auth` that you are using.

**Comment by MacWatrous** [comment]
I'm also having no luck and I've deployed the latest version of this repo. 

My error is 
```
[31m[auth][error][CallbackRouteError][0m: Read more at https://errors.authjs.dev#callbackrouteerror
[31m[auth][cause][0m: OperationProcessingError: "response" body "access_token" property must be a non-empty string
    at processGenericAccessTokenResponse (/var/task/.next/server/chunks/57.js:8396:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async processAuthorizationCodeOAuth2Response (/var/task/.next/server/chunks/57.js:8556:20)
    at async handleOAuth (/var/task/.next/server/chunks/57.js:9388:18)
    at async callback_callback (/var/task/.next/server/chunks/57.js:9522:41)
    at async AuthInternal (/var/task/.next/server/chunks/57.js:10347:38)
    at async Auth (/var/task/.next/server/chunks/57.js:10598:30)
    at async /var/task/.next/server/chunks/550.js:1087:37
[31m[auth][details][0m: {
  "provider": "github"
}
```

`package.json` and `pnpm-lock.yaml` both have version `0.0.0-manual.83c4ebd1` for `next-auth`

**Comment by balazsorban44** [comment]
@MacWatrous can you add a full reproduction, so I can take a look? As shown above, we have a deployed version now, working as expected, so there's likely something missing/misconfigured, I believe.

**Comment by MacWatrous** [comment]
Yes sorry for the late reply, I've made the repo public here: https://github.com/MacWatrous/ask-my-accounts-frontend

https://ask-my-accounts-frontend.vercel.app

**Comment by MacWatrous** [comment]
Ugh I just figured it out.. My `AUTH_GITHUB_SECRET` had a space in front of it. Everything is working for me now!

**Comment by sametcodes** [comment]
> Ugh I just figured it out.. My `AUTH_GITHUB_SECRET` had a space in front of it. Everything is working for me now!

This might be a case for you, but I'm having the same issue with OP.

**Comment by swyxio** [comment]
i think the issues are quite confusing. since a lot of them reference NEXTAUTH_URL, but now there is nothing in the template that is NEXTAUTH_URL

**Comment by imanirak** [comment]
Had this same issue, realized the wrong key was copied to the variable. So I had to update them and redeploy the website for changes to take effect.

**Comment by RushilJalal** [comment]
I'm facing the same issue as in the title. For me, Github Auth works perfectly locally, but stops working as soon as I deploy it on Vercel.
Can someone help me?
I created a discussion with all necessary errors here
https://github.com/nextauthjs/next-auth/discussions/11279

**Comment by shub-saini** [comment]
I also have the same issue. Locally everthing works but on vercel deployment github login does not work. I even changed my oauth url's to vercel url still issue persists.

**Comment by RushilJalal** [comment]
@shub-saini what is the version of Next being used in your project?
Downgrading the version fixed the issue for me

**Comment by shub-saini** [comment]
@RushilJalal I am using nextjs 14. I have now deployed my app on render platform and everything now correctly, the mean the github oauth provider. I issue is just with vercel. Thank you for the suggestion though, will try for future apps.
