### ISSUE TITLE
Could we please have a proper Function calling capability in this and a working GitHub login? Although I have a working GitHub login version Function calling doesn't work. 

### ISSUE THREAD

**Issue by ozgurozkan123** [vercel-labs/ai-chatbot#81]
Stream:true or false should be optional. 

Quick implementation via stream false would the best way to go.

**Comment by balazsorban44** [comment]
this sounds like 2 report in the title (might be worth rephrasing, as the second part should be working as expected. see https://github.com/vercel-labs/ai-chatbot/issues/89#issuecomment-1621630872 for a detailed explanation)

**Comment by ozgurozkan123** [comment]
Function calling is implemented closing this.
