### ISSUE TITLE
Current chat doesn't get saved when moving to another chat in history without page refresh

### ISSUE THREAD

**Issue by silvan-soeters** [vercel-labs/ai-chatbot#87]
Hi I'm (a first timer) looking into using this template but I noticed (in the demo) chats don't get saved to the history without refreshing the page. Not sure yet if I would be able to fix it so just thought I'd mention it. Hope that's ok.

Also, I'm getting a 404 page after clearing the history in the demo.

**Comment by silvan-digital** [comment]
Also, I'm getting a 404 page after clearing the history.

**Comment by EduardoFazolo** [comment]
> Hi I'm (a first timer) looking into using this template but I noticed (in the demo) chats don't get saved to the history without refreshing the page. Not sure yet if I would be able to fix it so just thought I'd mention it. Hope that's ok.

They get saved, but the ChatList component doesn't update. This is also kinda related to #79 which I partially solved with #88.
But while the PR isn't accepted, you can go to the `prompt-form` file and replace the `Link` component that creates a new chat for this:
```typescript
<button
  onClick={e => {
    e.preventDefault()
    router.refresh()
    router.push('/')
  }}
  className={cn(
    buttonVariants({ size: 'sm', variant: 'outline' }),
    'absolute left-0 top-4 h-8 w-8 rounded-full bg-background p-0 sm:left-4'
  )}
>
  <IconPlus />
  <span className="sr-only">New Chat</span>
</button>
```
This will, at least, show the previous chat in the history after you create a new chat. Let me know if this somewhat helped you.

**Comment by silvan-digital** [comment]
@EduardoFazolo Thanks(!), I will test this out when I start with the template and will let you know.

**Comment by QuantumSlipstream** [comment]
I've used react query to resolve this issue and it works pretty well.

**Comment by ilyakam** [comment]
@QuantumSlipstream, I got it to work by applying [your changes](https://github.com/vercel-labs/ai-chatbot/commit/b62f030aff0bff40db2185c813ba268dce93b11d), thanks!

For those who want to follow along, you'll need to switch away from the `'edge'` runtime in order for `@tanstack/react-query` to work correctly ([at least while in v4](https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5#no-longer-using-unstable_batchedupdates-as-the-batching-function-in-react-and-react-native)). You can learn more about that issue in https://github.com/TanStack/query/issues/5023.

**Comment by scottklein7** [comment]
@ilyakam @QuantumSlipstream Hey y'all! So i implemented the tansack changes and switched everything over to nodejs runtime, but I would get an exceeded runtime error in vercel logs (over 15 secs as I have a pro account). So i only switched the runtime in the chat.ts route back to edge, keeping everywhere else in nodejs, and it seem to still be working. I havent noticed any issues yet, but will that be a future problem?

**Comment by Saran33** [comment]
Anyone know why this feature is working fine on the demo site but those changes do not appear to be in source control? There also appears to be a recently added "New Chat" button in the chat list, for which I can't see any commits.
https://chat.vercel.ai/
