### ISSUE TITLE
How to implement persistence using local storage?

### ISSUE THREAD

**Issue by maddyonline** [vercel-labs/ai-chatbot#96]
Currently chat is persisted in KV store via `onCompletion` handler which is called in API route. Is there a way to call this handler in UI so chat can be persisted in local storage? AFAIK, you don't have access to local storage in API routes right? Thanks!

https://github.com/vercel-labs/ai-chatbot/blob/90180705e445a329473f1e2125955454c107b40c/app/api/chat/route.ts#L39

Any patterns for this will be appreciated.

**Comment by leerob** [comment]
Hey! We recommend storing this state in the database versus local storage. You are correct that API Routes don't have access to the browser local storage.
