### ISSUE TITLE
Error 405 when hitting api/chat endpoint

### ISSUE THREAD

**Issue by aalokpatwa** [vercel-labs/ai-chatbot#98]
I'm consistently getting a 405 error when trying to send a request to the api/chat endpoint for a chatCompletion streaming response. I'm not sure what's going on. The route returns 404 when trying to run it locally without deploying.

Here is the code for the route:
```
import { OpenAIStream, StreamingTextResponse } from 'ai'
import { Configuration, OpenAIApi } from 'openai-edge'

export const runtime = "edge";

const configuration = new Configuration({
  apiKey: "API"
})

const openai = new OpenAIApi(configuration)

export async function POST(req: Request) {
  const json = await req.json()
  const { messages } = json

  const res = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    messages,
    stream: true
  })

  const stream = OpenAIStream(res)

  return new StreamingTextResponse(stream)
}
```

I'm using the useChat() hook to send the request.

**Comment by lucasjinreal** [comment]
Same here

**Comment by krahal** [comment]
I fixed this bug after root-causing it to 2 issues:
1. My OpenAI API key was being disabled because I was pushing to a public repo. To fix this I made my repo private. 
2. I didn’t set my OpenAI API key in Vercel environment variables. You can do this via Settings > Environment Variables.

Hope this helps someone else.

**Comment by leerob** [comment]
^ Thanks for sharing back how you fixed the issue!

**Comment by enaros** [comment]
I'm having the same problem with a valid openai api key and a private repo, not sure why

**Comment by nckblu** [comment]
Remember to check your balance in OpenAI. Head to Settings, then Billing. It's the only place where you can spot if there's an issue with your limits, as it's not flagged up elsewhere in the OpenAI portal.

**Comment by KunalNasa** [comment]
Same issue
