### ISSUE TITLE
Method expects to have requestAsyncStorage, none available

### ISSUE THREAD

**Issue by Hosfad** [vercel-labs/ai-chatbot#99]
Hello i had to update to nextjs 13.4.8 to increase the     `serverActionsBodySizeLimit` , After updating i am getting the following error :
```
Error: Invariant: Method expects to have requestAsyncStorage, none available

components\header.tsx (18:28) @ auth

  16 | 
  17 | export async function Header() {
> 18 | const session: any =  auth()
     |                          ^
```
Any ideas how i can solve this ? while staying on 13.4.8 (Because its when the serverActionsBodySizeLimit was added) Thanks

**Comment by nukkerone** [comment]
Same, I upgraded nextjs and it's also happening to me:

![image](https://github.com/vercel-labs/ai-chatbot/assets/3185498/b7ddbae1-58e0-4d0a-b402-98082ab6c986)

**Comment by Hosfad** [comment]
@nukkerone Im guessing its a NextAuth issue, so for now I’m sticking with 13.4.7 and not using server actions

**Comment by micheltucker** [comment]
I found this other issue, which seems related: https://github.com/nextauthjs/next-auth/issues/6989

Server actions are a real head scratcher, but I somewhat figured them out now. Might be worth checking.

**Comment by dissorial** [comment]
I reworked the backend to use supabase for auth and data storage as opposed to next auth and vercel kv. I got the same error when upgrading to the latest version of Next, so I dont think its related to next-auth. One (suboptimal) way to solve this is to set your `export const runtime = ` to `nodejs` and not `edge`.

**Comment by satoshi02198** [comment]
Today, I got same error even It was worked fine. next version is 13.4.7. After changing 'edge' to 'nodejs' in everypage, it resolved.

**Comment by leerob** [comment]
Should be fixed in the latest PR to update all dependencies, using the new NextAuth.js v5 Beta: https://github.com/vercel-labs/ai-chatbot/pull/186
